name = "WebAssembly"
uuid = "4f6df8df-4739-5653-a877-cf57ee625c27"
version = "0.1.1"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
IRTools = "7869d1d1-7146-5819-86e3-90919afe41df"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
